[book]
title = "The Rust Programming Language (বাংলা অনুবাদ)"
authors = ["Steve Klabnik", "Carol Nichols", "Chris Krycho", "Contributions from the Rust Community"]
language = "bn"
description = "The Rust Programming Language বইটির সম্পূর্ণ বাংলা অনুবাদ (চলিত ভাষা)"
multilingual = false
src = "."

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/jafrulstc/rust_bangla_book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/jafrulstc/rust_bangla_book/edit/main/rust-book-bn/{path}"
additional-css = []
additional-js = []
no-section-label = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.fold]
enable = true
level = 0

[rust]
edition = "2024"

[build]
build-dir = "book"
create-missing = false
extra-watch-dirs = ["img"]
